---

  - name: Add apt key
    shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  
  - name: Add kubernetes to sources.list
    apt_repository: 
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present

  - name: Install kubelet kubeadm kubectl pip
    apt: 
      name: "{{ item }}"
      update_cache: yes
      state: present
      force: yes
    with_items:
      - kubelet={{ kube_version }} 
      - kubeadm={{ kube_version }}
      - kubectl={{ kube_version }}  
#      - kubernetes-cni={{ cni_version }}
    tags: install_kub

  - name: Ensure that cgroup driver is consistent
    tags: cgroup
    shell:
      cmd: |
        cat << EOF > /etc/docker/daemon.json
        {
          "exec-opts": ["native.cgroupdriver=cgroupfs"]
        }
        EOF

  - name: Ensure kubelet is started and enabled at boot.
    service:
      name: kubelet
      state: started
      enabled: yes

  - name: Enable routing in sysctl.conf
    lineinfile:
      path: /etc/sysctl.conf
      line: "{{ item }}"
    with_items:
      - 'net.bridge.bridge-nf-call-ip6tables=1'
      - 'net.ipv4.ip_forward=1'
      - 'net.bridge.bridge-nf-call-iptables=1'

  - name: Add VLANs
    shell: |
      modprobe 8021q
      vconfig add {{ uplink_iface}} {{ item }}
    args:
      creates: /proc/net/vlan/{{ uplink_iface }}.{{ item }}
    with_items:
      - "{{ infra_vlan }}"
      - "{{ node_vlan }}"

  - name: Edit /etc/network/interfaces
    template:
      src: templates/ubuntu-interfaces.j2
      dest: /etc/network/interfaces
      mode: '0644'
    tags: net
    notify: 
      - Restart server
      - Wait for server to restart

  - setup:
    tags: dhcp

  - name: Add dhclient options
    lineinfile:
      path: /etc/dhcp/dhclient.conf
      line: "{{ item }}"
      insertbefore: BOF
      state: present
    with_items:
      - "option rfc3442-classless-static-routes code 121 = array of unsigned integer 8;"
      - "option ms-classless-static-routes code 249 = array of unsigned integer 8;"
      - "option wpad code 252 = string;"
    tags: dhcp

  - name: Add Infra VLAN subinterface DHCP config
    blockinfile: 
      content: "{{ lookup('template', 'dhclient.conf.j2') }}"
      dest: /etc/dhcp/dhclient.conf
    tags: dhcp

#  - name: Remove default gateway for mgmt interface (DHCP)
#     template:
#      src: templates/dhclient-up-hooks.j2
#      dest: /etc/dhcp/dhclient-exit-hooks.d/dhclient-up-hooks
#      mode: '0644'
#    tags: net

  - name: Edit /etc/modules
    lineinfile:
      path: /etc/modules
      line: '8021q'
      state: present
 
  - name: Turn swap off
    shell: swapoff -a

  - name: Remove current swaps from fstab
    lineinfile:
      dest: /etc/fstab
      regexp: '(?i)^([^#][\S]+\s+(?:none|swap)\s+swap.*)'
      line: '# \1'
      backrefs: yes
      state: present
    notify:
      - Restart server
      - Wait for server to restart

  - name: Add host entry for node subnet
    lineinfile:
      dest: /etc/hosts
      line: "{{ node_ip_addr }}    {{ ansible_hostname }}"
      
    
