---

  - name: Add apt key
    shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  
  - name: Add kubernetes to sources.list
    apt_repository: 
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present

  - name: Install kubelet kubeadm kubectl pip
    apt: 
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items:
      - kubelet
      - kubeadm
      - kubectl  

  - name: Ensure that cgroup driver is consistent
    tags: cgroup
    shell:
      cmd: |
        cat << EOF > /etc/docker/daemon.json
        {
          "exec-opts": ["native.cgroupdriver=systemd"]
        }
        EOF

  - name: Ensure kubelet is started and enabled at boot.
    service:
      name: kubelet
      state: started
      enabled: yes
    tags: ACI

  - name: Enable routing in sysctl.conf
    lineinfile:
      path: /etc/sysctl.conf
      line: "{{ item }}"
    with_items:
      - 'net.bridge.bridge-nf-call-ip6tables=1'
      - 'net.ipv4.ip_forward=1'
      - 'net.bridge.bridge-nf-call-iptables=1'
    tags: ACI

  - name: Add VLANs
    command: " vconfig add {{ uplink_iface}} {{ item }}"
    args:
      creates: "/proc/net/vlan/{{ uplink_iface }}.{{ item }}"
    with_items:
      - "{{ mgmt_subint }}"
      - "{{ infra_subint }}"
      - "{{ node_vlan }}"
    tags: ACI

  - name: Edit /etc/network/interfaces
    template:
      src: templates/ubuntu-interfaces.j2
      dest: /etc/network/interfaces
      mode: '0644'
    tags: ACI

  - setup:
    tags: ACI

  - name: Add dhcp-client-identifier option
    lineinfile: 
      path: /etc/dhcp/dhclient.conf
      line: "send dhcp-client-identifier 1:{{ ansible_default_ipv4.macaddress }};"
      state: present
    tags: ACI

  - name: Edit /etc/modules
    lineinfile:
      path: /etc/modules
      line: '8021q'
      state: present
    tags: ACI

  - name: Restart machine
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true 
    tags: ACI

  - name: Change VM Network
    shell: ". {{ role_path }}/files/export_govc_env.sh && govc vm.network.change -vm={{ ansible_hostname }} -net={{ kubernetes_trunk_net }} ethernet-0"
    delegate_to: localhost
    tags: ACI

