---

  - name: Install specific packages
    yum: name={{ item }} state=present
    with_items:
      - ruby
      - ruby-devel
      - zlib-devel

  - name: Install gems (global)
    gem:
      name: "{{ item }}"
      state: present
      user_install: yes
      build_flags: "--no-ri --no-rdoc"
    with_items:
      - acirb
      - nokogiri
    become: no

  - name: Download Acirb
    get_url:
      url: https://github.com/datacenter/acirb/archive/master.zip
      dest: /tmp/acirb.zip
      use_proxy: yes
      validate_certs: no

  - name: Unzip Acirb
    unarchive: src=/tmp/acirb.zip dest=/tmp copy=no

  - name: Download Puppet Collection
    get_url:
      url: https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
      dest: /tmp/puppetlabs-release-pc1-el-7.noarch.rpm
      use_proxy: yes
      validate_certs: no

  - name: Install Puppet Collection
    yum: name=/tmp/puppetlabs-release-pc1-el-7.noarch.rpm state=present
    become: no

  - name: Install Puppet server
    yum: name=puppetserver state=present
    become: no

  - name: Install Acirb from Puppet gem binaries
    gem: executable=/opt/puppetlabs/puppet/bin/gem name=acirb build_flags="--no-rdoc --no-ri"

  - name: Install Acirb from Puppet command
    command: /opt/puppetlabs/bin/puppetserver gem install --local /tmp/acirb-master/gems/acirb-1.2.2.H.gem --no-rdoc --no-ri

  - name: Download APIC Puppet module
    get_url:
      url: https://github.com/cgascoig/puppet-aci/archive/master.zip
      dest: /tmp/puppet-aci.zip
      use_proxy: yes
      validate_certs: no

  - name: Unzip APIC Puppet module
    unarchive: src=/tmp/puppet-aci.zip dest=/tmp copy=no

  - name: Create folder structure
    file: path=~/.puppet/ state=directory recurse=yes

  - name: Configure device.conf
    template: src=device.conf.j2 dest=~/.puppet/device.conf

  - name: Configure site.pp
    template:
      src: site.pp.j2
      dest: /etc/puppetlabs/code/environments/production/manifests/site.pp

  - name: Configure puppet.conf
    template: src=puppet.conf.j2 dest=/etc/puppetlabs/puppet/puppet.conf

  - name: Configure /etc/hosts
    template: src=hosts.j2 dest=/etc/hosts

  - name: Ensure Puppet Server is up
    service: name=puppetserver state=started

  - name: Install ACI Puppet module
    shell: ./build.sh chdir=/tmp/puppet-aci-master

  - name: Generate CA CSR
    command: "{{ item }}"
    with_items:
      - /opt/puppetlabs/bin/puppet cert list -a

  - name: Add puppet device script
    template: src=puppetdevice.sh.j2 dest=/home/nvermand/puppetdevice.sh mode=a+x
