---

  - name: Install bash-completion pip
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - bash-completion
      - python-pip
    tags: master
      
  - name: Add bash completion to /etc/profile.d
    lineinfile:
      path: /etc/profile.d/bash_completion.sh
      line: 'source <(kubectl completion bash)'
    tags: master
 
  - name: Install acc_provision
    pip: 
      name: acc_provision
    tags: master
    
  - name: Create acc configuration file
    template:
      src: templates/aci-containers-config.yml.j2
      dest: /tmp/aci-containers-config.yml
      mode: '0777'
    tags: master

