---
  - name: Add jenkins repo
    get_url:
      url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: import gpg key
    rpm_key: state=present key=https://jenkins-ci.org/redhat/jenkins-ci.org.key

  - name: Install specific packages
    yum: state=present name={{ item }}
    with_items:
      - jenkins
      - java
      - epel-release
      - ansible
    register: result_sp
    tags:
      - last

  - name: Install pip
    yum: state=present name=python-pip
    register: result_pip
    when: result_sp|success

  - name: Install pysphere
    pip: name=pysphere
    when: result_pip|success

  # - name: Start jenkins
  #   service: state=started name=jenkins enabled=yes
