---

  - name: Install Python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: Check if SELinux installed
    shell: dpkg-query -s selinux | grep 'install ok installed'
    register: dpkg_check
    ignore_errors: yes
    tags:
      - configuration

  - name: Disable SELinux
    selinux: state=disabled
    when: dpkg_check == 0
    tags:
      - configuration

  - name: Install libselinux-python 
    apt: name=python-selinux state=present

  - name: Check if Firewalld is installed
    shell: dpkg-query -s firewalld | grep 'install ok installed'
    register: dpkg_check
    ignore_errors: yes
    tags:
      - configuration

  - name: Disable Firewalld
    service: name=firewalld enabled=no state=stopped
    when: dpkg_check == 0
    tags:
      - configuration

  - name: Install common packages
    apt: name={{ item }} state=present
    with_items:
      - unzip
      - wget
      - git
    tags:
      - configuration

  - name: restart machine
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
    tags:
      - configuration

  - name: Waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=60
    tags:
      - configuration
