---

  - name: Install Python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: Common tasks for Ubuntu
    include: common_ubuntu.yml
    when: ansible_distribution == "Ubuntu"

  - name: Common tasks for Centos
    include: common_centos.yml
    when: ansible_distribution == "CentOS"

  - name: Configure NTP
    template:
      src: ntp.conf.j2
      dest: /etc/ntp.conf
#    notify: restart ntp

  - name: restart machine
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
    tags:
      - configuration

#  - name: Waiting for server to come back
#    local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=60
#    tags:
#      - configuration
#
