---

  - name: Ensure old versions of Docker are not installed.
    package:
      name: '{{ item }}'
      state: absent
    with_items:
      - docker
      - docker-engine
      - docker.io

  - name: Install linux-image-extra
    apt:
      name: "{{ item }}"
      state: present
    with_items: 
      - linux-image-extra-{{ ansible_kernel }}
      - linux-image-extra-virtual

  - name: Ensure dependencies are installed.
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - software-properties-common

  - name: Add Docker apt key.
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    register: add_repository_key
    ignore_errors: true

  - name: Add Docker repository.
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present
      update_cache: yes

  - name: Install Docker.
    package: name=docker-ce state=present

  - name: Create docker.service.d
    file: 
      path: /etc/systemd/system/docker.service.d
      state: directory
    tags:
      - set_proxy
  
  - name: Create http-proxy.conf 
    template: src=templates/http-proxy.conf.j2 dest=/etc/systemd/system/docker.service.d/http-proxy.conf
    notify:
      - Restart docker
    tags:
      - set_proxy

  - name: Ensure Docker is started and enabled at boot.
    service:
      name: docker
      state: started
      enabled: yes

  - name: Add docker group
    group:
      name: docker
      state: present

  - name: Add user to docker group
    user:
      name: nvermand
      groups: docker
      append: yes

  - name: Install docker compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.17.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
      dest: /usr/local/bin/docker-compose

  - name: Make docker-compose executable
    file:
      path: /usr/local/bin/docker-compose
      mode: a+x
    tags:
      - compose_x

  - name: restart machine
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true

  - name: Waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=60
