---

  - name: Install Python 2
    raw:  test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: gather facts
    setup:

  - name: Install common packages
    apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - unzip
      - wget
      - git
      - bridge-utils

  - name: Ensure curl is present
    package: name=curl state=present
